name: build-release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run Build in a container
        uses: docker://gvfn/clang-buildpack:ubuntu-10
        with:
          entrypoint: /bin/bash
          args: |
            -c "\
            ./build-coverage.sh"

      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER ./build
          cat ./build/coverage/lcov.info
          sed -i -E  "s/\/github\/workspace\///g" build/coverage/lcov.info
          cat ./build/coverage/lcov.info

      - name: Push to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/coverage/lcov.info
