name: build-release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    contrainer: 

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run Build Coverage
        uses: docker://gvfn/clang-buildpack:ubuntu-10
        run: ./build-coverage.sh
