name: build-release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    contrainer: 
      image: gvfn/clang-buildpack:ubuntu-10
      volumes:
        - /home/runner/work/_temp/_github_home:/build:rw

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run Build in a container
        uses: docker://gvfn/clang-buildpack:ubuntu-10
        with:
          entrypoint: /bin/bash
          args: |
            -c "\
            ls -l
            cd /build
            ./build-coverage.sh"

      - name: Push to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage/lcov.info
