name: build-release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container: 
      image: gvfn/clang-buildpack:ubuntu-10
      options: --user root

    steps:
      # - name: Update permission
      #   run: |
      #     sudo chown -R $USER:$USER /home/runner/work/_temp
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run Build in a container
        uses: docker://gvfn/clang-buildpack:ubuntu-10
        with:
          entrypoint: /bin/bash
          args: |
            -c "\
            id -d &&
            id -u &&
            ls -l &&
            ./build-coverage.sh"

      - name: Push to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage/lcov.info
